name = "Botc Pack"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2bc7850a856dd42293546d94779ff50dbf09785f4089785e80094f004bfdda7"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
