name = "Botc Pack"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99a2db430b323f6497cd6bc21e44581b6639310aaf0f26a9c6492e22c39f0db5"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
